# Generated by Django 3.2.7 on 2021-09-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='stripe_customer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
