# Generated by Django 3.2.7 on 2021-09-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripes', '0003_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='paymentmethods',
            field=models.ManyToManyField(to='stripes.PaymentMethod'),
        ),
    ]
