# Generated by Django 3.2.7 on 2021-09-14 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripes', '0004_customer_paymentmethods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='paymentmethods',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stripes.customer'),
        ),
    ]
